Emprende/config/routes.rb
Rails.application.routes.draw do
  
  resources :sessions, only: [:new, :create, :destroy]
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
  
  

  resources :users
  get 'sessions/index'
  root 'sessions#index'


  resources :courses do
    resources :modulos
  end
  
  resources :courses do
    resources :tests
  end
   
  
end

Emprende/app/models/course.rb
class Course < ActiveRecord::Base
	has_many :modulos
	has_many :tests
end

Emprende/app/models/modulo.rb
class Modulo < ActiveRecord::Base
	belongs_to :course

end

Emprende/app/models/test.rb
class Test < ActiveRecord::Base
	belongs_to :course
end

Emprende/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  
  validates :first_name,
            presence: true
  validates :last_name,
            presence: true
  validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
  def to_s
    "#{first_name} #{last_name}"
  end


end

Emprende/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter :load_courses

  def load_courses
  	@courses = Course.all
  end
  protect_from_forgery with: :exception
  private
  def current_user
    User.where(id: session[:user_id]).first
  end
  helper_method :current_user
end

Emprende/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	def index
		@courses = Course.all
	end

	def show
		@course = Course.find params[:id]
	end

	
end

Emprende/app/controllers/modulos_controller.rb
class ModulosController < ApplicationController
	def index
		@course = Course.find params[:course_id]
		@modulos = @course.modulos
		
	end

	def show
		
		@course = Course.find params[:course_id]

		@modulos = Modulo.find params[:id]

			

	end

end

Emprende/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
   
  end
  
  def create
      user = User.find_by_email(params[:email])
      if user && user.authenticate(params[:password])
        session[:user_id] = user.id
        redirect_to courses_path
      else
        render :new
      end
  end



  def destroy
      session[:user_id] = nil
      redirect_to root_url
  end


end

Emprende/app/controllers/tests_controller.rb
class TestsController < ApplicationController
	def index
		@course = Course.find params[:course_id]
		@tests = @course.tests
	end

	def show
		@course = Course.find params[:course_id]
		@test = Test.find params[:id]

	end
end

Emprende/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  def index
    @users = User.all
  end

  def show
  end
  
  def new
    @user = User.new
  end
  
  def edit
  end
 
  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to courses_path
    else
      render :new
    end
  end
  
  def update
    if @user.update(user_params)
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render :edit
    end
  end


  def destroy
    @user.destroy
    redirect_to users_url, notice: 'User was successfully destroyed.'
  end

  private
    
    def set_user
      @user = User.find(params[:id])
    end

    
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
    end
end

Emprende/app/helpers/application_helper.rb
module ApplicationHelper
end

Emprende/app/helpers/courses_helper.rb
module CoursesHelper
end

Emprende/app/helpers/modulos_helper.rb
module ModulosHelper
end

Emprende/app/helpers/sessions_helper.rb
module SessionsHelper
end

Emprende/app/helpers/tests_helper.rb
module TestsHelper
end

Emprende/app/helpers/users_helper.rb
module UsersHelper
end

Emprende/app/views/courses/edit.html.erb
<h1>edit test</h1>

Emprende/app/views/courses/index.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
		<div class="inner cover">

	      <% @courses.each do |course| %>
	        <h3><%= link_to course.name, course_path(course) %></h3>
	        <div>Topic: <%= course.topic %></div>
        
      		<% end %>
    	</div>

</body>
</html>

Emprende/app/views/courses/show.html.erb
<div class="inner cover">
	<h2 class="cover-heading"><%= @course.name %></h2>
	<div>Temática: <%= @course.topic %></div>
	<div>Duration: <%= @course.duration %></div>
</div>

<p class="lead">
	<div class="btn btn-lg btn-info"><%= link_to "Modulos", course_modulos_path(@course) %></div>
</p>

<p class="lead">
	<div class="btn btn-lg btn-info"><%= link_to "Haz el test", course_tests_path(@course) %></div>
</p>

Emprende/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
  <title>Emprende</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag "application", media: 'all'  %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  
</head>
<body>

<div class="site-wrapper">
  <div class="site-wrapper-inner">
    <div class="cover-container">
      <div class="masthead clearfix">
        <div class="inner">
          <h3 class="masthead-brand">
            <div id="user_header">
              <% if current_user %>
                Logged in as <%= current_user.email %>.
                <%= link_to "Log Out", logout_path %>
              <% else %>
                <div class="btn btn-primary"><%= link_to "Únete", signup_path %></div> 
                <div class="btn btn-primary"><%= link_to "Inicia sesión", login_path %></div>
              <% end %>                  
            </div>
          </h3> 
          <nav>
          <h3>               
          <div class="nav masthead-nav">
        <% @courses.each_with_index do |course, index| %>
            <%= link_to "Curso "+(index+1).to_s, course_path(course), class: "btn btn-primary" %>
                  
          <% end %>
                      
          </div>
          </h3>
          </nav>


        </div>
      </div>             
   
         

      <% flash.each do |key, value| %>
        <%= content_tag(:div, class: "alert alert-#{key}") do %>
          <p><%= value %></p>
        <% end %>
      <% end %>
      <%= yield %>
                
      <div class="mastfoot">
        <div class="inner">
          <p>Project for <a href="http://ironhack.con">Ironhack</a>, by <a href="https://alejandroaldao.com">Alejandro Aldao</a>.</p>
        </div>
      </div>

    </div>
  </div>
</div>
    
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>

</body>
</html>
          

			
    
	

Emprende/app/views/modulos/index.html.erb
<h1>Curso: <%=@course.name %></h1>

<ul>
	<p><% @modulos.each do |modulo| %>
	Módulo: <%=link_to modulo.name, course_modulo_path(@course, modulo)%> | Tema <%=modulo.topic%></p>
	<%end%>
</ul>

Emprende/app/views/modulos/show.html.erb
<div class="container-modulos"
	<div class="row">
		<div class="col-md-6">
		   	<h3>Módulo: <%= @modulos.name %></h3><br>
		    <div>Temática: <%= @modulos.topic %></div><br>
		    <div>Introduction: <%= @modulos.introduction %></div><br>
		    <div>Discussion: <%= @modulos.discussion %></div>
		</div>

   
	    <div class="col-md-6">
		   	<img id="photo" src="<%= @modulos.image %>">
		</div>

	</div>
</div>

Emprende/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
     

<% end %>

Emprende/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Emprende/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellidos</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div class="btn btn-primary"><%= link_to 'New User', new_user_path %></div>

Emprende/app/views/users/new.html.erb
<div id="ground2">

<h2>Nuevo Usuario</h2>

<%= render 'form' %>

<br>


</div>

Emprende/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>